name: build module

on: [push]

jobs:
  build:

    runs-on: debian-testing
    
    steps:
    - uses: actions/checkout@v1
    - name: make
      run: make
    - name: make run-unit-tests
      run: make run-unit-tests